apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: script
type: Opaque
stringData:
    api-token: 7-Ai2uaoHWOGjZbERjMuBtgNMBKvO7Btqn4YxVF4

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  namespace: script # Your Coder deployment namespace
spec:
  acme:
    email: victorialslocum@gmail.com
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        cloudflare:
          email: me@bpmct.net
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            token: api-token

      # This section denotes which domains to use this issuer for. If you didn't
      # limit which zones the API token had access to, you may wish to remove
      # this section.
      selector:
        dnsZones:
          # Only use this issuer for the domain example.com and its subdomains.
          - 'victoria.coding.pics'
